eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
server:
  port: 8181

zuul:
  routes:
    facade:
      path: /**
      service-id: aggregator-service