server:
  port: 9999
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}

management:
  security:
    enabled: false

spring:
  boot:
    admin:
      context-path: "/admin/"